[phases.setup]
nixPkgs = [
  'python3', 
  'pip', 
  'nodejs', 
  'npm',
  'glib',
  'nss',
  'nspr',
  'atk',
  'at-spi2-atk',
  'libcups',
  'libxkbcommon',
  'xorg.libX11',
  'xorg.libXcomposite',
  'xorg.libXdamage',
  'xorg.libXext',
  'xorg.libXfixes',
  'xorg.libXrandr',
  'mesa',
  'cairo',
  'pango',
  'alsa-lib'
]

[phases.install]
cmds = [
  'pip install -r requirements.txt',
  './railway_build.sh'
]

[phases.build]
cmds = [
  'python3 manage.py collectstatic --noinput'
]

[start]
cmd = 'python3 setup_db.py && python3 railway_load_data.py && DJANGO_SETTINGS_MODULE=school_organizer.settings_production gunicorn school_organizer.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --worker-class sync --worker-connections 1000 --timeout 120 --preload'
