# Generated by Django 5.2.6 on 2025-09-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='important_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
