# Generated by Django 5.2.6 on 2025-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_add_created_by_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
