# Generated by Django 5.2.6 on 2025-09-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_add_schedule_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='organizer.subject'),
        ),
    ]
