# Generated by Django 5.2.6 on 2025-09-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_allow_null_subject_in_schedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together=set(),
        ),
    ]
