# Generated by Django 5.2.6 on 2025-09-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_remove_weeklyschedule_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('viewer', 'Viewer')], default='teacher', max_length=10),
        ),
    ]
