# Generated by Django 5.2.6 on 2025-09-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(blank=True, help_text='Display name for this user', max_length=50, null=True),
        ),
    ]
