# Generated by Django 5.2.6 on 2025-09-25 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_user_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyextra',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_extras', to='organizer.book'),
        ),
        migrations.AlterField(
            model_name='homeworkentry',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_entries', to='organizer.book'),
        ),
    ]
