# Generated by Django 5.2.6 on 2025-10-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyentry',
            options={'ordering': ['date', 'subject__name', 'position']},
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='position',
            field=models.IntegerField(default=0, help_text='Position when same subject appears multiple times per day'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together={('date', 'subject', 'created_by', 'position')},
        ),
    ]
